adjective = input("Enter an adjective(emotive): ")
Groom_name = input("Enter Groom's Name: ")
Bride_name = input("Enter Bride's Name: ")
adjective2 = input("Enter any adjective: ")
adjective3 = input("Enter any adjective: ")
adverb = input("Enter an adverb(describing verb): ")
verb = input("Enter a verb: ")
plural_noun = input("Enter a noun: ")
adverb2 = input("Enter another adverb: ")
verb2 = input("Enter another verb: ")
noun = input("Enter another noun: ")
adjective4 = input("Enter another adjective(emotive): ")
marriage_quote = input("Enter a relationship quote: ")
preposition = input("Enter a preposition: ")
proper_noun = input("Enter a Proper Noun: ")
your_name = input("Enter your name: ")


print("I am so " + adjective + " "  "for" " " + Groom_name + " " "and" " " + Bride_name + "!")
print("They are the most" " " + adjective2 + " "  "couple that I know of.")
print("My best advice for the" " " + adjective3 + " " "couple is" " " + Groom_name + ",")
print("you should" " " + adverb + " " + verb + " " + Bride_name + "'s" " " + plural_noun + ".")
print(Bride_name + "," " " "you should" " " + adverb2 + " " + verb2 + " " + Groom_name + "'s" " " + noun + ".")
print("I am so" " " + adjective4 + " " "for you both!")
print("Remember," " " + marriage_quote)
print("Have a wonderful time"  " " + preposition + " " + proper_noun + "!")
print("Love," " " + your_name)
